### ISSUE TITLE
dist/shopify-buy.common.js has incorrect require paths

### ISSUE THREAD

**Issue by mikkoh** [Shopify/js-buy-sdk#187]
The `shopify-buy.common.js` does not work when attempting to consume it. You will get the following error:

```
Error: Cannot find module '../ajax'
    at Function.Module._resolveFilename (module.js:339:15)
    at Function.Module._load (module.js:290:25)
    at Module.require (module.js:367:17)
    at require (internal/module.js:16:19)
    at Object.<anonymous> (/Users/mikkohaapoja/Documents/learning/test-umd-js-buy-sdk/shopify-buy.commonjs.js:34:13)
    at Module._compile (module.js:413:34)
    at Object.Module._extensions..js (module.js:422:10)
    at Module.load (module.js:357:32)
    at Function.Module._load (module.js:314:12)
    at Module.require (module.js:367:17)
```

I've noticed this same issue when doing UMD builds so maybe we'll get two birds with one stone.

**Comment by mikkoh** [comment]
Ok some progress on this issue. In the https://github.com/Shopify/js-buy-sdk/tree/feature/build-system branch I've been setting up for umd builds. 

To test that branch check it out and then do.
```bash
$ npm i
$ npm run build-production
```
This will build out a umd + amd build. The amd build will be used for testing and the umd build can be potentially distributed to the CDN.

My major concern with the UMD build would be the file size increase. But it turns out that it remains at a reasonable size at 19kb minified and 65kb non-minified.
