### ISSUE TITLE
[BUG] npm install fails

### ISSUE THREAD

**Issue by dmitrybelyakov** [Shopify/js-buy-sdk#61]
Trying to install from npm and getting lots of exceptions and deprecated  warnings.

```
npm WARN package.json onfood-wordpress-theme@1.1.0 No repository field.
npm WARN deprecated socket.io-pure@1.3.12: socket.io-pure is no longer maintained as the original socket.io removed all native dependencies. Please use the original.
npm WARN deprecated lodash@2.3.0: lodash@<3.0.0 is no longer maintained. Upgrade to lodash@^4.0.0.
npm WARN deprecated engine.io-pure@1.5.9: engine.io-purce is no longer maintained as the original engine.io removed all native dependencies. Please use the original.
npm WARN deprecated socket.io-client-pure@1.3.12: socket.io-client-pure is no longer maintained as the original socket.io removed all native dependencies. Please use the original.
npm WARN deprecated ws-pure@0.8.0: ws-pure is no longer maintained as the original ws removed all native dependencies. Please use the original ws.
npm WARN deprecated engine.io-client-pure@1.5.9: engine-io-client-pure is no longer maintained as the original engine-io-client removed all native dependencies. Please use the original.
```

and then finally dies with:

```
.../node_modules/shopify-buy/build-lib/lib.js:5
const funnel = require('broccoli-funnel');
^^^^^
SyntaxError: Use of const in strict mode.
    at exports.runInThisContext (vm.js:73:16)
    at Module._compile (module.js:443:25)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (module.js:384:17)
    at Object.<anonymous> (.../node_modules/shopify-buy/Brocfile.js:16:12)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
```

**Comment by richgilbank** [comment]
@dmitrybelyakov Which version of node are you running currently? Raises a good point that our supported node versions aren't documented. @minasmart What is the current support? Could we be using `babel-register` in here to transpile the required build scripts?

**Comment by minasmart** [comment]
Hey there! This looks like a node compatibility issue.

We support the current version of node, back to 5.8. I'm pretty sure v4 will work too back to v4.3.2, but that hasn't been tested.

As for NPM, version 3 and up is what's required.

@richgilbank if supporting older versions of node is desired, we can certainly link in babel-register. While working on the build scripts, I was only using post IO.js versions of node.

**Comment by dmitrybelyakov** [comment]
Hey, @minasmart thanks for that! That worked.
