### ISSUE TITLE
Fetch is not defined in production - Netlify

### ISSUE THREAD

**Issue by Elswell** [Shopify/js-buy-sdk#935]
I am working on a project using the ShopifyStorefrontApi as well as the shopify-buy npm package.

Netlify functions work flawlessly on the localhost, but once everything is deployed I am getting a reference error that fetch is not defined. When the create-cart function gets executed, which is on first page load, I store the data in localStorage. But instead i can see what error it returns in the localStorage:

`{"errorType":"ReferenceError","errorMessage":"fetch is not defined","trace":["ReferenceError: fetch is not defined","    
at Client3.fetcher (/var/task/netlify/functions/create-cart.js:1163:9)","    at Client3.send (/var/task/netlify/functions/create-cart.js:1260:23)","    
at CheckoutResource2.create (/var/task/netlify/functions/create-cart.js:7897:37)","    at Runtime.handler (/var/task/netlify/functions/create-cart.js:8899:45)","   
at Runtime.handleOnceNonStreaming (file:///var/runtime/index.mjs:1089:29)"]}`

It points towards the create-cart function, but I am not using fetch there, so from there I believe it leads to the shopifyClient. I been stuck on this for many hours. Any help will be appreciated.

![ad1a80457888515e1a8e17e9d816ad7708f2aaa3](https://user-images.githubusercontent.com/80487621/212539639-9a20633f-7aab-4ad2-a4e8-f9ea5e308328.png)

**Comment by Elswell** [comment]
If anybody comes by the same problem. Do this in netlify:

"Set AWS_LAMBDA_JS_RUNTIME environment variable in the UI with the value nodejs18.x."
