### ISSUE TITLE
postinstall script exhausts the CPU and eventually fails on Windows 10

### ISSUE THREAD

**Issue by petetnt** [Shopify/js-buy-sdk#97]
Trying to install `shopify-buy` on a Windows 10 PC straight from the Github repo (https://github.com/Shopify/js-buy-sdk/commit/f085e51ae2092dbefc1a7f98304d581175ccfc4b)

```
npm install https://github.com/Shopify/js-buy-sdk --save
```

When the `postinstall` script starts running, massive amounts of CPU processing power and memory start to get used:

![image](https://cloud.githubusercontent.com/assets/7641760/14769533/7e8a83aa-0a63-11e6-9a71-ef8eff4d8aa7.png)

and eventually the script fails with this:

``` bash
> ./scripts/postinstall

'.' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! Windows_NT 10.0.10586
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "install" "https://github.com/Shopify/js-buy-sdk" "--save"
npm ERR! node v5.1.0
npm ERR! npm  v3.3.12
npm ERR! code ELIFECYCLE

npm ERR! shopify-buy@0.1.3 postinstall: `./scripts/postinstall`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the shopify-buy@0.1.3 postinstall script './scripts/postinstall'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the shopify-buy package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     ./scripts/postinstall
npm ERR! You can get their info via:
npm ERR!     npm owner ls shopify-buy
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\foo\npm-debug.log
```

Occurs on both cmd.exe and Git Bash.

**Comment by petetnt** [comment]
Most likely also resolved by #95

**Comment by yoadsn** [comment]
I confirm the same when installing on a clean package.json (but nothing special in terms of high CPU - just the same error from postintall).
Windows 10 - using git bash.

I have merged locally `build-on-pre-publish`  and got the same error now from the `prepublish` script:

```
> ./scripts/prepublish

'.' is not recognized as an internal or external command,
operable program or batch file.
```

So I assume #95 would not solve this for windows users if they are to publish the package. (I don't have a linux machine to test the publish now, I assume this is working fine).

The root issue here are the "scripts" folder using by npm to build/publish etc. They rely on bash to run them, which (even if you run npm from git bash) is not available in windows CMD.. the default shell for npm on windows.
Even if you do force the default shell to be the git bash, the call to "npm tun build" from within the prepublish script itself runs in a windows CMD shell (which again, does not have bash).
This is a mix of weird compatibility issues that could be avoided using node scripts for the build process which are (mostly) xplat... take this into consideration if you want to make this build windows friendly..

**Comment by petetnt** [comment]
Regardless of the build scripts themselves, `broccoli-lint-eslint` needs to be updated to `2.2.1` too as `2.2.0` is broken on Windows too.

Even that isn't enough as after that `broccoli` fails on:

```
D:\foo\node_modules\shopify-buy>"node_modules/.bin/broccoli"  build dist
File: ajax.js
ReferenceError: [BABEL] ajax.js: Unknown option: D:\foo\.babelrc.presets
    at Logger.error (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\logger.js:58:11)
    at OptionManager.mergeOptions (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:126:29)
    at OptionManager.addConfig (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:107:10)
    at OptionManager.findConfigs (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:168:35)
    at OptionManager.init (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\options\option-manager.js:229:12)
    at File.initOptions (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\index.js:147:75)
    at new File (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\file\index.js:137:22)
    at Pipeline.transform (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\node_modules\babel-core\lib\transformation\pipeline.js:164:16)
    at Babel.transform (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\index.js:94:21)
    at Babel.processString (D:\foo\node_modules\shopify-buy\node_modules\broccoli-babel-transpiler\index.js:123:25)

Build failed
```

**Comment by minasmart** [comment]
Part of this is addressed by #102.

@petetnt: Can you point me at reference to `broccoli-lint-eslint@2.2.0` being broken on windows? I'll bump the version, I just want a bug that I can point to in the PR.

Thanks @petetnt and @yoadsn! All of your investigative work here is really appreciated.

**Comment by petetnt** [comment]
@minasmart This is the commit: https://github.com/ember-cli/broccoli-lint-eslint/commit/1b300cdea8a2e7d4c7219ffe59642d804fbd2b37 and this is the issue https://github.com/ember-cli/broccoli-lint-eslint/issues/35

Thanks @minasmart :+1:

**Comment by minasmart** [comment]
Awesome! Thank you!
